### ISSUE TITLE
API Version Out of Date

### ISSUE THREAD

**Issue by Fraycore** [thorwe/teamspeak-plugin-radiofx#2]
Not sure if you are still around, but your plugin has an out of date API version now with the latest TeamSpeak update.

**Comment by thorwe** [comment]
Will look into it.

**Comment by Fireant456** [comment]
Any eta on an update? Been missing my radiofx :'(

**Comment by JGarrett01** [comment]
Looking forward to getting this to work with the newest TS update.

**Comment by timcard** [comment]
Thanks to look into it. I stay tuned. Thanks :)

**Comment by onelz232** [comment]
Is there any update on when the pluggin will be updated on teamspeak browse?

**Comment by thorwe** [comment]
Unless I discover a blocking issue until then: If not tomorrow, sometime early next week.
I also snuck in some code improvements while at it, you know, for the suspense 🍿

**Comment by onelz232** [comment]
tnx for updating the plugin on teamspeak its good
