### ISSUE TITLE
Radio FX not working

### ISSUE THREAD

**Issue by WhyYouBanMe** [thorwe/teamspeak-plugin-radiofx#4]
Hi! 
I wanted to let you know, that Radio FX isn't working on some ts servers, but on other it works. I doesn't work on my friend's teamspeak, and we don't know why. Maybe you can help me solving this problem, beacause our Fivem partnerships want to have a radio on their server.

**Comment by MichaelMeikle** [comment]
It has something to do with TeamSpeak's recent client id change, in which the numbers no longer overlap but increasingly get larger. After the value gets over the max positive value that a short can hold, 32,767, radiofx starts experiencing issues. Periodic TeamSpeak restarts will prevent this problem from appearing at least until there is a fix implemented by the actual developer.

**Comment by thorwe** [comment]
Thanks for the hint @MichaelMeikle, I think I know already where that's coming from then. Some years ago, there was a bug where whispers came in on a negative sign, i.e. client id 3 would be unsigned world uint16_t::max() -3. I implemented a workaround for that which made some assumption about high client id values to correct that and, while the bug afaik is fixed now, there wasn't a reason to remove it - until now.

Edit: Bingo
https://github.com/thorwe/teamspeak-plugin-qt-common/blob/master/core/plugin_base.cpp#L231

Being in core, all my plugins will need updating. I'll dust the build environment on my private machine after work.

**Comment by thorwe** [comment]
Hm, I'm not sure if that's all of it though.
At that position it just should result in a bad sound (ironically), not cause it to not work at all.
Well, I guess we'll see..

Edit (again):
Wait, yes it will, cause the lookup for the dsp effect instance will fail. Nothing to see here, move along... ;)

**Comment by thorwe** [comment]
Ok, I've only done a tiny bit of testing, but things appear to be back to working...
Packages should be up on myteamspeak the upcoming week, then the update should trigger automatically.

**Comment by thorwe** [comment]
finally up on myteamspeak, should auto update.
